version: '2'
services:
  elasticsearch:
    image: "elasticsearch:5.5.1"
    environment:
      discovery.type: zen
      discovery.zen.ping.unicast.hosts: elasticsearch
      #    ports:
      #- "9200:9200"
    volumes:
     - "./elasticsearch/data:/usr/share/elasticsearch/data"
     - "./elasticsearch/logs:/usr/share/elasticsearch/logs"

  kibana:
    image: "kibana:5.5.1"
    environment:
      elastisearch.url: "http://elasticsearch:9200"
    ports:                                                                                                               
     - "5601:5601"

  logstash:
    image: "docker.elastic.co/logstash/logstash:5.5.2"
    ports:
     - "5140:5140"
     - "5140/udp:5140/udp"
    volumes:
     - "./logstash/config/logstash.yml:/usr/share/logstash/config/logstash.yml"
     - "./logstash/pipeline:/usr/share/logstash/pipeline"
     - "./logstash/etc:/usr/share/logstash/etc"
